apiVersion: pulumi.com/v1alpha1
kind: Stack
metadata:
  name: nginx-k8s-stack
  namespace: operator
spec:
  envRefs:
    PULUMI_ACCESS_TOKEN:
      type: Secret
      secret:
        name: pulumi-api-secret
        namespace: operator
        key: accessToken
  stack: jpke/nginx/dev
  projectRepo: https://github.com/metral/pulumi-nginx
  commit: 2b0889718d3e63feeb6079ccd5e4488d8601e353
  destroyOnFinalize: true