apiVersion: pulumi.com/v1alpha1
kind: Stack
metadata:
  name: s3-bucket-stack
  namespace: operator
spec:
  envRefs:
    PULUMI_ACCESS_TOKEN:
      type: Secret
      secret:
        name: pulumi-api-secret
        namespace: operator
        key: accessToken
    # AWS_ROLE_ARN:
    #   type: Env
    #   env:
    #     name: AWS_ROLE_ARN 
    # AWS_WEB_IDENTITY_TOKEN_FILE:
    #   type: Filesystem
    #   filesystem:
    #     path: AWS_WEB_IDENTITY_TOKEN_FILE 
    AWS_ACCESS_KEY_ID:
      type: Secret
      secret:
        name: pulumi-aws-secrets
        namespace: operator
        key: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      type: Secret
      secret:
        name: pulumi-aws-secrets
        namespace: operator
        key: AWS_SECRET_ACCESS_KEY
    ACCESSTOKENSECRET:
      type: Secret
      secret:
        name: pulumi-aws-secrets
        namespace: operator
        key: AWS_SECRET_ACCESS_KEY
  stack: jpke/s3-op-project/dev
  accessTokenSecret: pulumi-api-secret
  projectRepo: https://github.com/jpke/test-s3-op-project.git
  commit: 374ca2947c3be1177580c8e72a480ec0bffb71e9
  config:
    aws:region: us-east-1
